HomeForm


<div class="frm-content"><label>*Имя, фамилия</label>[text firstname class:input-text]<div class="clear_both"></div><label>*Телефон</label>[text phone1 class:input-text]<div class="clear_both"></div><label>*E-mail</label>[text email class:input-text]<div class="clear_both"></div><label class="wide">Текст обращения</label>[textarea message class:txt-msg]<div class="submit-btn">[submit "Отправить"]</div></div>



SidebarForm


<td><div class="FeedbackCaption"><span class="asterics">*</span> Имя, фамилия</div></td></tr><tr><td class="FeedbackFormInputs">[text firstname id:fullname class:inputBoxTxt class:FeedbackInput]<div class="FeedbackInfo" id="fullname_info" style="cursor: pointer;"><img border="0" alt="" src=" http://assuta.dev/wp-content/themes/wp-assuta/img/info-btn.gif" vspace="2px"></div></td></tr><tr><td class="FeedbackCaption"><span class="asterics">*</span> Страна</td></tr><tr><td class="FeedbackFormInputs">[select country id:country "Выберите страну" "Россия" "Украина" "Казахстан" "Израиль" "Другая"]<div id="country_info" class="FeedbackInfo" style="padding-top: 5px; padding-left: 12px; cursor: pointer;"><img src=" http://assuta.dev/wp-content/themes/wp-assuta/img/info-btn.gif" alt="" border="0"></div></td></tr><tr><td class="FeedbackCaption"><span class="asterics">*</span> Телефон</td></tr><tr><td class="FeedbackFormInputs">[text c_phone1 id:fullname class:inputBoxTxt class:FeedbackInput]<div id="phone_info" class="FeedbackInfo" style="padding-top: 5px; cursor: pointer;padding-left: 6px;"><img src=" http://assuta.dev/wp-content/themes/wp-assuta/img/info-btn.gif" alt="" border="0"></div></td></tr><tr><td class="FeedbackCaption"><span class="asterics">*</span> E-mail</td></tr><tr><td class="FeedbackFormInputs" colspan="2">[text email id:fullname class:inputBoxTxt class:FeedbackInput]<div id="email_info" class="FeedbackInfo" style="padding-top: 5px; cursor: pointer;"><img src=" http://assuta.dev/wp-content/themes/wp-assuta/img/info-btn.gif" alt="" border="0"></div></td></tr><tr><td class="FeedbackCaption">Текст обращения</td></tr><tr><td class="FeedbackFormInputs">[textarea message id:message class:inputBoxTxt1]<div id="note_info" class="FeedbackInfo" style="padding-top: 5px; vertical-align: top; cursor: pointer;"><img src=" http://assuta.dev/wp-content/themes/wp-assuta/img/info-btn.gif" alt="" border="0"></div></td></tr><tr><td align="left">[submit]</td>




FAQ

<table cellpadding="0" cellspacing="0" border="0" width="100%"><tr valign="top"><td class="ContactFormTitles"><div class="ContactFormTitles"><span class="asterics">*</span>Имя</div></td><td class="ContactFormTitles" style="padding-left:17px;"><div class="ContactFormTitles"><span class="asterics">*</span>Фамилия</div></td></tr><tr><td class="ContactFormInputs">[text firstname class:inputBoxTxt]<div id="first_name_info" style="display: inline; cursor: pointer;"><img src="http://assuta.dev/wp-content/themes/wp-assuta/img/info-btn.gif" alt="" border="0"></div></td><td class="ContactFormInputs" style="padding-left:23px;">[text lastname class:inputBoxTxt]<div id="last_name_info" style="display: inline; cursor: pointer;"><img src="http://assuta.dev/wp-content/themes/wp-assuta/img/info-btn.gif" alt="" border="0"></div></td></tr><tr valign="top"><td class="ContactFormTitles"><div class="ContactFormTitles"><span class="asterics">*</span>Страна:</div></td><td class="ContactFormTitles" style="padding-left:23px;"><div class="ContactFormTitles"><span class="asterics">*</span>Тел.</div></td></tr><tr><td class="ContactFormInputs">[select country id:country "Выберите страну" "Россия" "Украина" "Казахстан" "Израиль" "Другая"]<div id="country_info" style="display: inline; cursor: pointer;"><img src="http://assuta.dev/wp-content/themes/wp-assuta/img/info-btn.gif" alt="" border="0"></div></td><td class="ContactFormInputs" style="padding-left:23px;">[text c_phone1 class:inputBoxTxt]<div id="phone_info" style="display: inline; cursor: pointer;"><img src="http://assuta.dev/wp-content/themes/wp-assuta/img/info-btn.gif" alt="" border="0"></div></td></tr><tr valign="top" colspan="2"><td class="ContactFormTitles"><div class="ContactFormTitles"><span class="asterics">*</span>E-mail</div></td></tr><tr><td class="ContactFormInputs" colspan="2">[text email class:inputBoxTxt]<div id="email_info" style="display: inline; cursor: pointer;"><img src="http://assuta.dev/wp-content/themes/wp-assuta/img/info-btn.gif" alt="" border="0"></div></td></tr><tr valign="top"><td class="ContactFormTitles" colspan="4"><div class="ContactFormTitles">Текст обращения</div></td></tr><tr><td colspan="2" class="ContactFormInputs">[textarea message class:inputBoxTxt1]<div id="note_info" style="display: inline; vertical-align: top; cursor: pointer;"><img src="http://assuta.dev/wp-content/themes/wp-assuta/img/info-btn.gif" alt="" border="0" style="vertical-align:top"></div></td></tr><tr><td style="padding-bottom:40px;" align="left" colspan="2">[submit "Отправить"]</td></tr></table>
